# Site settings
title: Qubes OS Project
description: "Qubes OS is an open source operating system designed to provide strong security for desktop computing using Security by Compartmentalization approach. Qubes is based on Xen, X Window System, and Linux, and can run most Linux applications and utilize most of the Linux drivers. It can also run Windows apps natively in Windows AppVMs (Beta)."
repository: "https://github.com/QubesOS/qubesos.github.io"
help_url: "https://github.com/Nukama/nukama.github.io/wiki"

# Build settings
timezone: UTC
encoding: utf-8
markdown: kramdown
highlighter: pygments
relative_permalinks: false
permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""

collections:
#  docs:
#    output: true
  wiki:
    output: true
  hcl:
    output: false
  author:
    output: true
