# Site settings
title: Qubes OS
description: > # this means to ignore newlines until "baseurl:"
  Qubes is a security-oriented, free and open-source operating system for
  personal computers that allows you to securely compartmentalize your digital
  life.
twitter_username: QubesOS
github_username:  QubesOS
# Project Settings
project_url: "https://www.qubes-os.org"
project_repo_path: "https://github.com/QubesOS"
project_repo_site: "/qubesos.github.io"
project_repo_wiki: "/qubes-wiki"
project_repo_artwork: "/qubes-artwork"

# Build settings
markdown: kramdown
highlighter: rouge
timezone: UTC
encoding: utf-8
relative_permalinks: false
permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

collections:
  doc:
    output: true
    permalink: /doc/:path/
  hcl:
    output: false

allowed_categories:
  - press
  - announcements
  - releases
  - articles
  - security
  - talks

default_author: "The Qubes OS Team"
default_category: "announcements"
